name: Build Plugin

# Triggers the workflow on push for the master branch
on: 
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          
      - name: maven-settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "github", "username": "dummy", "password": "${GITHUB_TOKEN_REF}"}]'
          githubServer: false
                  
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        env:
          GITHUB_TOKEN_REF: ${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}
        
      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          path: target/*.jar
          name: Package
